### ISSUE TITLE
DHCP Option 82 (Relay Agent Information) is missing.

### ISSUE THREAD

**Issue by s3rj1k** [gopacket/gopacket#25]
It seems that DHCPv4 Option 82 (Relay Agent Information) and  Sub Options are missing, to be in pair with `github.com/insomniacslk/dhcp/dhcpv4` by functionality.

**Comment by s3rj1k** [comment]
cc: @aibor

**Comment by s3rj1k** [comment]
I am willing to do a PR with some helpers for option 82 and sub-options, if no one is going to work on this.

**Comment by aibor** [comment]
Since you put me in cc on this issue: I'm not working on this, so, go ahead.

**Comment by s3rj1k** [comment]
> Since you put me in cc on this issue: I'm not working on this, so, go ahead.

I saw that you did some fixes around relay in recent patches, thought you would be interested, hence the CC. :)

**Comment by mosajjal** [comment]
go for it! draft a PR :)

**Comment by s3rj1k** [comment]
Sadly things happened that are out of my control and the project that I was working on that used `gopacket` lacks me as a maintainer, so it does not sound that I would be able to test-out any contributions to `gopacket`.

P.S. If someone gets interested on one of example usages, look here: https://github.com/Mirantis/dhcp-relay/issues/13
