### ISSUE TITLE
Feature Request: Embed fmt.Stringer interface into the Router interface

### ISSUE THREAD

**Issue by shaunco** [gopacket/gopacket#46]
The internal implementation of `router` has a really nice `String()` function. It would be very helpful for runtime logging if this was exposed so the `Router` interface objects can be used in calls that expect a `fmt.Stringer`

**Comment by mosajjal** [comment]
I'm not opposed to this. but adding the Stringer to the interface is a breaking change that needs a new version (2.x) to be in place. I'm ok with a new Interface (eg RouterStringer) to be considered in the meantime but won't merge it into the current interface.
