### ISSUE TITLE
FR - File handle minimum delay and original packet delay options

### ISSUE THREAD

**Issue by ikiris** [gopacket/gopacket#49]
Feature request:

When using a file based capture, instead of feeding packets as fast as possible, provide options to insert either original packet delay, or a static delay. possibly a minimum delay option as well when using original.

I realize I could do this myself by making an interface wrapper, but it seems like something worth requesting upstream.

**Comment by mosajjal** [comment]
if your use case is to replay a PCAP stream, that won't be in scope for gopacket. I intend to keep this library as minimal as possible
