### ISSUE TITLE
SEGFAULT when getting layer payload

### ISSUE THREAD

**Issue by jkmancuso** [gopacket/gopacket#71]
Hi, first time reporting an issue here so apologies if there's any missing info or context. Basically, both of these two lines below are the problem

(https://github.com/jkmancuso/home_sniffer/blob/main/packet_capture.go#L80-L81)
packet.NetworkLayer().LayerPayload()
packet.ApplicationLayer().LayerPayload()

NetworkLayer() and ApplicationLayer() work fine until I try to grab the layer payload. Getting

 **panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3cd834]**

It may be relevant to add that this is running on a Raspberry PI with Debian 12. 
Linux raspberrypi 6.6.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
go version go1.22.3 linux/arm64
using gopacket v1.2.0

**Comment by mcoops** [comment]
Hrmm, it's a bit tough from the description and without the packets that are causing it, but you could update both those layer gets with something like:

```golang
if netlayer := packet.NetworkLayer(); netLayer == nil {
   // skip
}
```

In case you have packets without a network layer in your network like ARPs maybe? If you're only interested in IP traffic you could get the Ethernet layer and check the type.

**Comment by jkmancuso** [comment]
you were right @mcoops , ARP and some ICMP packets were the problem. Easily filtered it out: 

`handle.SetBPFFilter("port 53 or port 443") `

Last question- I'm trying to capture the DNS query and DNS response, but unable to see the payload. Any idea how to get it? Im trying to cast LayerPayload bytes as a string but maybe that's a naive approach.

msg="Getting packet: PACKET: 171 bytes, wire length 171 cap length 171 @ 2024-06-30 10:50:53.365422083 -0400 EDT\n- Layer 1 (14 bytes) = Ethernet\t{Contents=[..14..] Payload=[..157..] SrcMAC=f8:bb:bf:33:94:d2 DstMAC=2c:cf:67:27:49:a6 EthernetType=IPv4 Length=0}\n- Layer 2 (20 bytes) = IPv4\t{Contents=[..20..] Payload=[..137..] Version=4 IHL=5 TOS=0 Length=157 Id=10756 Flags=DF FragOffset=0 TTL=63 Protocol=UDP Checksum=34575 SrcIP=192.168.1.1 DstIP=192.168.7.235 Options=[] Padding=[]}\n- Layer 3 (08 bytes) = UDP\t{Contents=[..8..] Payload=[..129..] SrcPort=53(domain) DstPort=39311 Length=137 Checksum=4269}\n- Layer 4 (129 bytes) = DNS\t{Contents=[..129..] Payload=[] ID=8801 QR=true OpCode=Query AA=false TC=false RD=true RA=true Z=0 ResponseCode=No Error QDCount=1 ANCount=1 NSCount=1 ARCount=0 Questions=[{Name=[..25..] Type=Unknown Class=IN}] Answers=[{Name=[..25..] Type=CNAME Class=IN TTL=213 DataLength=17 Data=[..17..] IP=<nil> NS=[] CNAME=[..36..] PTR=[] TXTs=[] SOA={ MName=[] RName=[] Serial=0 Refresh=0 Retry=0 Expire=0 Minimum=0} SRV={ Priority=0 Weight=0 Port=0 Name=[]} MX={ Preference=0 Name=[]} OPT=[] URI={ Priority=0 Weight=0 Target=[]} TXT=[]}] Authorities=[{Name=[..23..] Type=SOA Class=IN TTL=40 DataLength=45 Data=[..45..] IP=<nil> NS=[] CNAME=[] PTR=[] TXTs=[] SOA={ MName=[..14..] RName=[..20..] Serial=647927117 Refresh=900 Retry=900 Expire=1800 Minimum=60} SRV={ Priority=0 Weight=0 Port=0 Name=[]} MX={ Preference=0 Name=[]} OPT=[] URI={ Priority=0 Weight=0 Target=[]} TXT=[]}] Additionals=[]}\n\n\n"

msg="transport layer \"a\x81\x80\x00\x01\x00\x01\x00\x01\x00\x00\x03lh3\x11googleusercontent\x03com\x00\x00A\x00\x01\xc0\f\x00\x05\x00\x01\x00\x00\x00\xd5\x00\x11\fgooglehosted\x01l\xc0\x10\xc0D\x00\x06\x00\x01\x00\x00\x00(\x00-\x03ns1\x06google\xc0\"\tdns-admin\xc0X&\x9e\x95M\x00\x00\x03\x84\x00\x00\x03\x84\x00\x00\a\b\x00\x00\x00<"

msg="app layer \"a\x81\x80\x00\x01\x00\x01\x00\x01\x00\x00\x03lh3\x11googleusercontent\x03com\x00\x00A\x00\x01\xc0\f\x00\x05\x00\x01\x00\x00\x00\xd5\x00\x11\fgooglehosted\x01l\xc0\x10\xc0D\x00\x06\x00\x01\x00\x00\x00(\x00-\x03ns1\x06google\xc0\"\tdns-admin\xc0X&\x9e\x95M\x00\x00\x03\x84\x00\x00\x03\x84\x00\x00\a\b\x00\x00\x00<"
