### ISSUE TITLE
afpacket.(*TPacket).ReadPacketData segmentation violation

### ISSUE THREAD

**Issue by RyougikiMikiya** [gopacket/gopacket#78]
version:tags v1.2.0
go version: go1.22.5
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fd1acc1c00c pc=0x3c24b56]

goroutine 74 gp=0xc00324c380 m=2 mp=0xc00009c808 [running]:
runtime.throw({0x49387d8?, 0x0?})
        runtime/panic.go:1023 +0x5c fp=0xc0009f6ad0 sp=0xc0009f6aa0 pc=0x43e93c
runtime.sigpanic()
        runtime/signal_unix.go:895 +0x285 fp=0xc0009f6b30 sp=0xc0009f6ad0 pc=0x457385
github.com/gopacket/gopacket/afpacket.(*v3wrapper).next(0xc0031a8308?)
        github.com/gopacket/gopacket@v1.2.0/afpacket/header.go:256 +0x16 fp=0xc0009f6b40 sp=0xc0009f6b30 pc=0x3c24b56
github.com/gopacket/gopacket/afpacket.(*TPacket).ZeroCopyReadPacketData(0xc0031a8240)
        github.com/gopacket/gopacket@v1.2.0/afpacket/afpacket.go:324 +0xde fp=0xc0009f6bd8 sp=0xc0009f6b40 pc=0x3c230fe
github.com/gopacket/gopacket/afpacket.(*TPacket).ReadPacketData(0x2c5db2d1d8d4850?)
        github.com/gopacket/gopacket@v1.2.0/afpacket/afpacket.go:439 +0x73 fp=0xc0009f6ca8 sp=0xc0009f6bd8 pc=0x3c23c13
asm/pkg/lscanner/ethhandle.(*AfpacketHandle).ReadPacketData(0xcccccccccccccccc?)
        asm/pkg/lscanner/ethhandle/afpackethandle.go:73 +0x70 fp=0xc0009f6d50 sp=0xc0009f6ca8 pc=0x3c25b90
github.com/gopacket/gopacket.PacketDataSource.ReadPacketData-fm()
        <autogenerated>:1 +0x85 fp=0xc0009f6df8 sp=0xc0009f6d50 pc=0x3ac4965
github.com/gopacket/gopacket.(*PacketSource).NextPacket(0xc00324a690)
        github.com/gopacket/gopacket@v1.2.0/packet.go:943 +0x58 fp=0xc0009f6f00 sp=0xc0009f6df8 pc=0x3ac0c98
github.com/gopacket/gopacket.(*PacketSource).packetsToChannel(0xc00324a690, {0x617e858, 0xc003217860})
        github.com/gopacket/gopacket@v1.2.0/packet.go:960 +0xab fp=0xc0009f6fb8 sp=0xc0009f6f00 pc=0x3ac0eeb
github.com/gopacket/gopacket.(*PacketSource).PacketsCtx.gowrap1()
        github.com/gopacket/gopacket@v1.2.0/packet.go:1026 +0x28 fp=0xc0009f6fe0 sp=0xc0009f6fb8 pc=0x3ac1368
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc0009f6fe8 sp=0xc0009f6fe0 pc=0x4793c1
created by github.com/gopacket/gopacket.(*PacketSource).PacketsCtx in goroutine 72
        github.com/gopacket/gopacket@v1.2.0/packet.go:1026 +0xd6
        
I found that there are many similar issues in the Google repository's issues [section](https://github.com/google/gopacket/issues?q=is%3Aissue+is%3Aopen+SIGSEGV).

**Comment by RyougikiMikiya** [comment]
I sincerely apologize for the inconvenience caused, the issue arose due to my utilization of a socket that had already been closed. ReadPacketData(0xcccccccccccccccc?) is a wild pointer

**Comment by FeldrinH** [comment]
I'd still say there's a bug in afpacket. A Go function shouldn't segfault even if misused.
