### ISSUE TITLE
What's the relationship between google/gopacket and this project?

### ISSUE THREAD

**Issue by Misaka-Mikodo** [gopacket/gopacket#86]
Hi, I had read [this issue](https://github.com/google/gopacket/issues/1016) but still a little confuse about the relationship between google/gopacket and this project. I wonder that if I want to use gopacket, and which version should I get? google/gopacket or this project? (gopacket/gopacket)
It seems that google/gopacket had stopped update in two years ago, and this project is active recently, maybe those two are the same packet and this repo is the newest version of gopacket?

**Comment by mosajjal** [comment]
Hi. It's completely up to you which version you'd like to use. AFAIK `google/gopacket` is not currently maintained. There's always a chance that it will get maintained again by Google. Meanwhile, I forked it into `gopacket/gopacket`. I help maintain it, add new features, fix bugs, refactor the code and maintain the quality, security and support of the code and Go version. 

I'm the sole maintainer of this project, and I have a 9 to 5 job unrelated to coding so my hope is to find more maintainers for `gopacket` and leave it to the community to run and maintain.
