### ISSUE TITLE
Potentially invalid use of #ifdef

### ISSUE THREAD

**Issue by ssgelm** [gopacket/gopacket#89]
In https://github.com/gopacket/gopacket/commit/94ad652445d73076cfbf84a5b6d3674828565dd2, code was added to check for 64-bit time. The following code was added in order to check for the existence of a type:

```c
#ifdef __time64_t
```

The problem with this, as far as I'm aware, is that you cannot use `ifdef` to check whether a type has been defined. See further discussion here[^1]. Was there a particular reason this code was added? It breaks builds on 32-bit systems with 64-bit time enabled.

[^1]: https://stackoverflow.com/questions/6772802/in-c-c-is-there-a-directive-similar-to-ifndef-for-typedefs.

**Comment by ssgelm** [comment]
FYI I got the build working successfully on Debian by replacing the line with:
```c
#if defined(__USE_TIME64_REDIRECTS) || (__TIMESIZE == 32 && __USE_TIME_BITS64)
```

**Comment by TochusC** [comment]
#92
