### ISSUE TITLE
DNSSEC Support

### ISSUE THREAD

**Issue by TochusC** [gopacket/gopacket#91]
Hello everyone,

I am currently a college student exploring DNSSEC. I’ve noticed that there is a lack of DNSSEC support in the existing `layers/dns.go` file. Which makes it unable to send and receive DNSSEC-enabled DNS messages. So, I forked the original `google/gopacket` repository and implemented DNSSEC in my fork `tochusc/gopacket`.

I would like to submit a pull request to `gopacket/gopacket` to add DNSSEC support. Could I?

**Comment by mosajjal** [comment]
Hi,

please raise it as a draft PR and I'll take a look. from high level looks doable.

**Comment by TochusC** [comment]
I have submitted a PR [#92](https://github.com/gopacket/gopacket/pull/92#issue-2593516967). Currently, I have only implemented the RRSIG and DNSKEY Resource Records for basic use.

DNSSEC introduces four new resource record types: DS, RRSIG, DNSKEY, and NSEC. Additionally, future RFCs also introduce two more types: NSEC3 and NSEC3PARAM.

I would like to implement these additional resource records as soon as I can.

**Comment by TochusC** [comment]
I have also noticed that the current `dns.go` file does not allow sending unknown type Resource Records (RR). 

DNS is a field where new features are frequently developed, so it would be very useful if gopacket enabled us to craft and send any kind of RR we want. 

Implementing this is straightforward; it only requires changing four lines of code in the `encode` and `recSize` functions to add a default case.

I could also draft a PR for this. Is it plausible?
