### ISSUE TITLE
pcap.h not found

### ISSUE THREAD

**Issue by ea7kir** [gopacket/gopacket#95]
Forgive me, but if I don't ask I won't learn.
```
pi@repctl:~/GO-PACKET $ go mod tidy
pi@repctl:~/GO-PACKET $ go run .
# github.com/gopacket/gopacket/pcap
../go/pkg/mod/github.com/gopacket/gopacket@v1.3.0/pcap/pcap_unix.go:35:10: fatal error: pcap.h: No such file or directory
   35 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
```
This on examples: afpacket.go and pfdump.go ( the only 2 I've tried)
Raspberry Pi 4, PiOS Lite (Bookworm)

Should I be installing some dependancies, if so, what?  Or, is it some other problem?

**Comment by wader** [comment]
Yes try install https://packages.debian.org/bookworm/libpcap-dev

**Comment by ea7kir** [comment]
Thanks @wader .  This has fixed the issue.

**Comment by ea7kir** [comment]
@wader now missing pfring.h with example pfddump.go

```
../go/pkg/mod/github.com/gopacket/gopacket@v1.3.0/pfring/pfring.go:14:10: fatal error: pfring.h: No such file or directory
   14 | #include <pfring.h>
```

**Comment by wader** [comment]
Don't know about pfring and it does not seem to be in debian, maybe here somewhere? https://packages.ntop.org/apt-stable/

**Comment by mosajjal** [comment]
`pfring` is not a requirement by default in any downstream application/library using `gopacket` unless explicitly imported. are you sure the code you're writing doesn't need `pfring`? if it does, you need to install pfring libraries on your system.

**Comment by ea7kir** [comment]
@mosajjal I've tried a couple of the examples so far.   My ultimate goal is to write a "simple" package that will send to channel one of two messages:  
1) an rtmp stream has connected, and 2) the stream has disconnected.
The stream source is known and fixed, but it comes and goes when it likes.
The source address, which works on VLC, is of the form:
rtmp://example.com/live/name

**Comment by mosajjal** [comment]
there are plenty of projects not using CGO and making `gopacket` work. you might need to tweak your code. I don't believe this is a `gopacket` issue unless there are more specific defects.
